# https://taskfile.dev
version: "3"

vars:
  ENV: esp32s3
  UPLOAD_PORT: /dev/cu.usbserial-410
  BAUD: 115200
  OTA_HOST: giant-esp32.local
  PIO: '{{.PIO | default "~/.platformio/penv/bin/pio"}}'

tasks:
  default:
    desc: Build firmware
    cmds:
      - '{{.PIO}} run -e {{.ENV}}'

  build:
    desc: Build firmware
    cmds:
      - '{{.PIO}} run -e {{.ENV}}'

  flash:
    desc: Build and flash firmware to ESP32
    cmds:
      - '{{.PIO}} run -e {{.ENV}} -t upload --upload-port {{.UPLOAD_PORT}}'

  monitor:
    desc: Open serial monitor
    cmds:
      - '{{.PIO}} device monitor --port {{.UPLOAD_PORT}} --baud {{.BAUD}}'

  deploy:
    desc: Build, flash, and open serial monitor
    cmds:
      - task: flash
      - task: monitor

  clean:
    desc: Clean build artifacts
    cmds:
      - '{{.PIO}} run -e {{.ENV}} -t clean'

  devices:
    desc: List connected serial devices
    cmds:
      - ls /dev/cu.usb*

  ota:
    desc: Build and flash firmware over WiFi (OTA)
    cmds:
      - '{{.PIO}} run -e {{.ENV}} -t upload --upload-port {{.OTA_HOST}}'
